# Generated by Django 5.0.4 on 2024-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nostage', models.CharField(max_length=20)),
                ('typestage', models.CharField(max_length=20)),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('nbreplace', models.IntegerField()),
                ('nbreinscrit', models.IntegerField()),
            ],
        ),
    ]
