# Generated by Django 5.0.4 on 2024-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codestage', models.IntegerField()),
                ('numstagiaire', models.IntegerField()),
                ('dateinsc', models.IntegerField()),
                ('statusinscr', models.CharField(max_length=20)),
                ('codeposition', models.IntegerField()),
            ],
        ),
    ]
