# Generated by Django 5.0.4 on 2024-05-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='stage',
            field=models.CharField(max_length=10),
        ),
    ]
